// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HomeAssistantKnob

#ifndef _HOMEASSISTANTKNOB_UI_H
#define _HOMEASSISTANTKNOB_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * test_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Nunito);
LV_FONT_DECLARE(ui_font_NunitoItalic20);
LV_FONT_DECLARE(ui_font_Montserrat80);
LV_FONT_DECLARE(lv_font_roboto_extralight_150);

// IMAGES
LV_IMG_DECLARE(icon_fan);
LV_IMG_DECLARE(icon_list);

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_update_temperature(int new_temp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
