// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HomeAssistantKnob

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_KleurAchtergrond[2] = {0x000000, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_KleurAchtergrond[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_KleurAccentKoud[2] = {0x00E5FF, 0x00E5FF};
const ui_theme_variable_t _ui_theme_alpha_KleurAccentKoud[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_KleurAccentWarm[2] = {0xFF9F0A, 0xFF9F0A};
const ui_theme_variable_t _ui_theme_alpha_KleurAccentWarm[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

