// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HomeAssistantKnob

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ArcDoel;
extern lv_obj_t * ui_ArcHuidig;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_TempIndicatorC;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_Temperature1;
extern lv_obj_t * ui_Temperature2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Arc1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

