// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HomeAssistantKnob

#include "../ui.h"

lv_obj_t * uic_Arc1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ArcDoel = NULL;
lv_obj_t * ui_ArcHuidig = NULL;
lv_obj_t * ui_Temp = NULL;
lv_obj_t * ui_TempIndicatorC = NULL;
lv_obj_t * ui_Temperature = NULL;
lv_obj_t * ui_Temperature1 = NULL;
lv_obj_t * ui_Temperature2 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ArcDoel = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcDoel, 360);
    lv_obj_set_height(ui_ArcDoel, 360);
    lv_obj_set_align(ui_ArcDoel, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcDoel, 10, 30);
    lv_arc_set_value(ui_ArcDoel, 20);
    lv_obj_set_style_arc_color(ui_ArcDoel, lv_color_hex(0x1C1C1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcDoel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcDoel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_ArcDoel, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_KleurAccentKoud);
    ui_object_set_themeable_style_property(ui_ArcDoel, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_KleurAccentKoud);
    lv_obj_set_style_arc_width(ui_ArcDoel, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_ArcDoel, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_KleurAccentKoud);
    ui_object_set_themeable_style_property(ui_ArcDoel, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_KleurAccentKoud);
    lv_obj_set_style_pad_left(ui_ArcDoel, -1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcDoel, -1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcDoel, -1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcDoel, -1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcHuidig = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcHuidig, 360);
    lv_obj_set_height(ui_ArcHuidig, 360);
    lv_obj_set_align(ui_ArcHuidig, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcHuidig, 10, 30);
    lv_arc_set_value(ui_ArcHuidig, 20);
    lv_obj_set_style_arc_color(ui_ArcHuidig, lv_color_hex(0x1C1C1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHuidig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcHuidig, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcHuidig, lv_color_hex(0x00E5FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHuidig, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcHuidig, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcHuidig, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcHuidig, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcHuidig, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcHuidig, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcHuidig, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcHuidig, -5, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Temp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp, "27");
    lv_obj_set_style_text_font(ui_Temp, &ui_font_Montserrat80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempIndicatorC = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TempIndicatorC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempIndicatorC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempIndicatorC, 84);
    lv_obj_set_y(ui_TempIndicatorC, 11);
    lv_obj_set_align(ui_TempIndicatorC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempIndicatorC, "°C");
    lv_obj_set_style_text_font(ui_TempIndicatorC, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature, 0);
    lv_obj_set_y(ui_Temperature, 100);
    lv_obj_set_align(ui_Temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temperature, "Temperature");
    lv_obj_set_style_text_font(ui_Temperature, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Temperature1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature1, 0);
    lv_obj_set_y(ui_Temperature1, 120);
    lv_obj_set_align(ui_Temperature1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temperature1, "21");
    lv_obj_set_style_text_font(ui_Temperature1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Temperature2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature2, 10);
    lv_obj_set_y(ui_Temperature2, 120);
    lv_obj_set_align(ui_Temperature2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temperature2, "°C");
    lv_obj_set_style_text_font(ui_Temperature2, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Arc1 = ui_ArcDoel;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_Arc1 = NULL;
    ui_ArcDoel = NULL;
    ui_ArcHuidig = NULL;
    ui_Temp = NULL;
    ui_TempIndicatorC = NULL;
    ui_Temperature = NULL;
    ui_Temperature1 = NULL;
    ui_Temperature2 = NULL;

}
